### ISSUE TITLE
Hide issue not clickable after navigation

### ISSUE THREAD

**Issue by JStuve** [JStuve/git-kit#11]
**Describe the bug**
When navigating back to the issue board, the eye icon is not clickable to hide.

**To Reproduce**
1. Go to the issue board
2. Click an issue
3. Click the back arrow to go back to the issue board
4. Click the eye icon

**Expected behavior**
This issue should be hidden after clicked

**Comment by TallanGroberg** [comment]
I would like to work on this task.
